const Instrument = require('../models/Instrument');

const instrumentData = [
    { name: `voice` },
    { name: `chu daiko` },
    { name: `shime daiko` },
    { name: `o daiko` },
    { name: `afghani guitar` },
    { name: `alghoza` },
    { name: `accordion` },
    { name: `bagpipes` },
    { name: `banjo` },
    { name: `banjo cello` },
    { name: `bass banjo` },
    { name: `five-stringed banjo` },
    { name: `bluegrass banjo` },
    { name: `four-stringed banjo` },
    { name: `plectrum banjo` },
    { name: `six-stringed banjo` },
    { name: `tenor banjo` },
    { name: `zither banjo` },
    { name: `bass guitar` },
    { name: `bassoon` },
    { name: `contrabassoon/double bassoon` },
    { name: `tenoroon` },
    { name: `berimbau` },
    { name: `bongo` },
    { name: `chimta` },
    { name: `cello` },
    { name: `clarinet` },
    { name: `alto clarinet` },
    { name: `bass clarinet` },
    { name: `basset clarinet` },
    { name: `basset horn` },
    { name: `clarinette d'amour` },
    { name: `contra-alto clarinet` },
    { name: `contrabass clarinet` },
    { name: `piccolo clarinet` },
    { name: `a♭ clarinet` },
    { name: `sopranino clarinet` },
    { name: `e♭ clarinet` },
    { name: `d clarinet` },
    { name: `soprano clarinet` },
    { name: `c clarinet` },
    { name: `b♭ clarinet` },
    { name: `a clarinet` },
    { name: `g clarinet` },
    { name: `octocontra-alto clarinet` },
    { name: `octocontrabass clarinet` },
    { name: `clavichord` },
    { name: `cor anglais` },
    { name: `cornet` },
    { name: `cymbal` },
    { name: `dhime` },
    { name: `didgeridoo` },
    { name: `dizi` },
    { name: `double bass` },
    { name: `drum kit` },
    { name: `esraj` },
    { name: `ektara` },
    { name: `erhu` },
    { name: `euphonium` },
    { name: `fiddle` },
    { name: `flute` },
    { name: `alto flute` },
    { name: `bass flute` },
    { name: `contra-alto flute` },
    { name: `contrabass flute` },
    { name: `subcontrabass flute` },
    { name: `double contrabass flute` },
    { name: `hyperbass flute` },
    { name: `french horn` },
    { name: `ghatam` },
    { name: `box drum` },
    { name: `glass harmonica` },
    { name: `glockenspiel` },
    { name: `gong` },
    { name: `guitar` },
    { name: `acoustic guitar` },
    { name: `baritone guitar` },
    { name: `bass guitar` },
    { name: `chitarra battente` },
    { name: `cigar box guitar` },
    { name: `classical guitar` },
    { name: `electric guitar` },
    { name: `electric bass guitar` },
    { name: `extended-range guitars` },
    { name: `alto guitar` },
    { name: `seven-string guitar` },
    { name: `eight-string guitar` },
    { name: `ten-string guitar` },
    { name: `harp guitar` },
    { name: `flamenco guitar` },
    { name: `fusetar` },
    { name: `guitarra quinta huapanguera` },
    { name: `guitar synthesizer` },
    { name: `guitarrón (argentino)` },
    { name: `guitarrón (chileno)` },
    { name: `guitarrón (mexicano)` },
    { name: `guitarrón (uruguayo)` },
    { name: `gut-stringed guitars` },
    { name: `lap steel guitars` },
    { name: `dobro` },
    { name: `national steel` },
    { name: `multi-necked guitars` },
    { name: `double-neck guitar` },
    { name: `triple-neck guitar` },
    { name: `quadruple-neck guitar` },
    { name: `five-neck guitar` },
    { name: `six-neck guitar` },
    { name: `seven-neck guitar` },
    { name: `eight-neck guitar` },
    { name: `rock ock` },
    { name: `twelve-neck guitar` },
    { name: `nine-string guitar` },
    { name: `nylon-string guitars` },
    { name: `octave guitar` },
    { name: `pedal steel guitar` },
    { name: `resophonic guitar` },
    { name: `steel-string acoustic guitar` },
    { name: `tenor guitar` },
    { name: `terz guitar` },
    { name: `twelve-string guitar` },
    { name: `yotar` },
    { name: `guqin` },
    { name: `guzheng` },
    { name: `hang` },
    { name: `harmonica` },
    { name: `chromatic harmonica` },
    { name: `diatonic harmonica` },
    { name: `tremolo harmonica` },
    { name: `orchestral harmonica` },
    { name: `chengong harmonica` },
    { name: `harmonium` },
    { name: `harp` },
    { name: `harpsichord` },
    { name: `hammered dulcimer` },
    { name: `hulusi` },
    { name: `hurdy gurdy` },
    { name: `indian banjo` },
    { name: `jew’s harp` },
    { name: `kalimba` },
    { name: `lute` },
    { name: `lyre` },
    { name: `mandolin` },
    { name: `mando-bass` },
    { name: `mandocello` },
    { name: `mandola` },
    { name: `octave mandolin` },
    { name: `marimba` },
    { name: `melodica` },
    { name: `oboe` },
    { name: `bass/baritone oboe` },
    { name: `contrabass oboe` },
    { name: `cor anglais/english horn` },
    { name: `oboe d'amore` },
    { name: `oboe da caccia` },
    { name: `piccolo oboe/oboe musette` },
    { name: `ocarina` },
    { name: `transverse ocarina` },
    { name: `pendant ocarina` },
    { name: `inline ocarina` },
    { name: `multi chambered ocarina` },
    { name: `keyed ocarina` },
    { name: `slide ocarina` },
    { name: `octobass` },
    { name: `organ` },
    { name: `otamatone` },
    { name: `oud` },
    { name: `pan pipes` },
    { name: `panduri` },
    { name: `pennywhistle` },
    { name: `piano` },
    { name: `piccolo` },
    { name: `pipa` },
    { name: `pungi` },
    { name: `rabab or rubab` },
    { name: `recorder` },
    { name: `garklein` },
    { name: `sopranino` },
    { name: `descant` },
    { name: `treble or alto` },
    { name: `tenor` },
    { name: `bass` },
    { name: `great bass` },
    { name: `contra bass` },
    { name: `subcontra bass` },
    { name: `sub-subcontrabass` },
    { name: `venova` },
    { name: `sarangi` },
    { name: `sarinda` },
    { name: `suroz` },
    { name: `sursinger` },
    { name: `santoor` },
    { name: `sarod` },
    { name: `saxophone` },
    { name: `alto saxophone` },
    { name: `baritone saxophone` },
    { name: `bass saxophone` },
    { name: `c melody saxophone` },
    { name: `c soprano saxophone` },
    { name: `contrabass saxophone` },
    { name: `mezzo-soprano saxophone (alto in f)` },
    { name: `sopranino saxophone` },
    { name: `soprano saxophone` },
    { name: `soprillo` },
    { name: `subcontrabass saxophone` },
    { name: `tenor saxophone` },
    { name: `tubax` },
    { name: `venova` },
    { name: `xaphoon` },
    { name: `shehnai` },
    { name: `sheng` },
    { name: `sitar` },
    { name: `steelpan` },
    { name: `stylophone` },
    { name: `suona` },
    { name: `synthesizer` },
    { name: `tabla` },
    { name: `tambourine` },
    { name: `timpani` },
    { name: `florguitar` },
    { name: `triangle` },
    { name: `trombone` },
    { name: `sopranino trombone` },
    { name: `soprano trombone` },
    { name: `alto trombone` },
    { name: `tenor trombone` },
    { name: `bass trombone` },
    { name: `contrabass trombone` },
    { name: `valve trombone` },
    { name: `renaissance trombone` },
    { name: `trumpet` },
    { name: `soprano trumpet` },
    { name: `bass trumpet` },
    { name: `baroque trumpet` },
    { name: `bass trumpet` },
    { name: `rotary valve trumpet` },
    { name: `theremin` },
    { name: `thundertube (spring drum)` },
    { name: `tuba` },
    { name: `bass tuba` },
    { name: `contrabass tuba` },
    { name: `subcontrabass tuba` },
    { name: `ukulele` },
    { name: `pocket ukulele` },
    { name: `soprano ukulele` },
    { name: `concert ukulele` },
    { name: `tenor ukulele` },
    { name: `eight-string tenor` },
    { name: `five-string tenor` },
    { name: `lili'u` },
    { name: `six-string tenor` },
    { name: `baritone ukulele` },
    { name: `bass ukulele` },
    { name: `contrabass ukulele` },
    { name: `u-bass` },
    { name: `cigar box ukulele` },
    { name: `veena` },
    { name: `viola` },
    { name: `violin` },
    { name: `piccolo violino` },
    { name: `viola` },
    { name: `viola d'amore` },
    { name: `tenor viola` },
    { name: `tenor violin` },
    { name: `baritone violin` },
    { name: `electric violin` },
    { name: `cello (violoncello)` },
    { name: `piccolo cello` },
    { name: `whamola` },
    { name: `xylophone` },
    { name: `zither` },
    { name: `alpine zither (harp zither)` },
    { name: `concert zither` },
    { name: `guitar zither` },
    { name: `overtone zither` },
];

const seedInstruments = () => Instrument.bulkCreate(instrumentData);

module.exports = seedInstruments;